FROM python:3

ADD requirements.txt /jqueuing/requirements.txt
ADD experiment_operations.py /jqueuing/experiment_operations.py
ADD experiment_manager.py /jqueuing/experiment_manager.py
ADD monitoring.py /jqueuing/monitoring.py
WORKDIR /jqueuing/
RUN pip install -r requirements.txt
RUN pip install -U "celery[redis]"
ENTRYPOINT python3 experiment_feeder.py 1 customer_app 1 2 3