version: '2'
services:
    redis:
        image: "redis:alpine"

    stastd:
        image: prom/statsd-exporter
        container_name: statsd
        expose:
            - 9125
            - 9102
    
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
            - ./config/prometheus/:/etc/prometheus/
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
        expose:
            - 9090
        ports:
            - 9090:9090

    grafana:
        image: grafana/grafana
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        volumes:
            - ./data/grafana:/var/lib/grafana
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=foobar
            - GF_USERS_ALLOW_SIGN_UP=false

    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5673:5672"

    queuing_manager:
        build:
            context: .
            dockerfile: Dockerfile_QM
        volumes:
            - .:/qmanager
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - rabbit
            - redis
        depends_on:
            - rabbit
            - redis
        ports:
            - "5599:5599"
        expose:
            - 8777

    experiment_feeder:
        build:
            context: .
            dockerfile: Dockerfile_EFeeder
        volumes:
            - .:/efeeder
        links:
            - queuing_manager
        depends_on:
            - queuing_manager
