version: '2'
services:
    redis:
        image: "redis:alpine"

    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5673:5672"

    queuing_manager:
        build:
            context: .
            dockerfile: Dockerfile_QM
        volumes:
            - .:/qmanager
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - rabbit
            - redis
        depends_on:
            - rabbit
            - redis
        ports:
            - "5599:5599"

    container_feeder:
        build:
            context: .
            dockerfile: Dockerfile_CFeeder
        volumes:
            - .:/cfeeder
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - queuing_manager
        depends_on:
            - queuing_manager

    job_feeder:
        build:
            context: .
            dockerfile: Dockerfile_JFeeder
        volumes:
            - .:/jfeeder
        links:
            - queuing_manager
        depends_on:
            - queuing_manager
            - container_feeder
